# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /workdir

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    libpq-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --upgrade pip

RUN pip install "audio-separator[cpu]"

# Run audio-separator when the container launches
ENTRYPOINT ["audio-separator"]
